---   # https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0-1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.11.1
    hooks:
      - id: "yamllint"

  - repo: https://github.com/IamTheFij/ansible-pre-commit.git
    rev: v0.1.2
    hooks:
      - id: "encryption-check"

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.3.0
    hooks:
      - id: php-lint
      - id: php-unit
      - id: php-cs
        files: \.(php)$
        args: [--standard=PSR1 -p]
      - id: php-cbf
        files: \.(php)$
        args: [--standard=PSR1 -p]

  - repo: https://github.com/pre-commit/mirrors-csslint.git
    rev: 'v1.0.5'
    hooks:
      - id: csslint

  - repo: https://github.com/pre-commit/mirrors-jshint.git
    rev: 'v2.9.6'
    hooks:
      - id: jshint

  # Does not work on windows
  - repo: https://github.com/willthames/ansible-lint.git
    sha: v3.4.23
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args: [
          "--exclude=roles",
          "--exclude=.travis.yml"
        ]
