---

- hosts: all:localhost
  roles:
    - profiles

- hosts: localhost

  tasks:
    - include_tasks: deploy-debian.yml
      become: yes
      become_method: sudo
      when: ansible_os_family == 'Debian'
      tags: package

