--- # deployment of devops workstation

- hosts: all:localhost
  roles:
    # profiles

- hosts: localhost

  tasks:

    - include_tasks: deploy-debian.yml
      become: yes
      become_method: sudo
      when: ansible_os_family == 'Debian'
      tags: package

    - name: install extra user pip modules 
      pip:
        name: '{{ item }}'
        executable: pip2
        extra_args: --user
      with_items:
        - boto3    # https://boto3.readthedocs.io/en/latest/guide/quickstart.html
        - awscli   # http://docs.aws.amazon.com/cli/latest/userguide/getting-help.html
        - molecule # https://molecule.readthedocs.io
        - pylint
        - httpstat
        - googler
        - speedtest_cli


    - name: install vagrant plugins
      command: "vagrant plugin install {{ item }}"
      with_items:
        - vagrant-aws
