---

- hosts: all
  roles:
    - profiles

- hosts: all

  tasks:
    - include: deploy-debian.yml
      become: yes
      become_method: sudo
      when: ansible_os_family == 'Debian'
      tags: package

