--- # deployment of devops workstation

# | jq --raw-output .tag_name"

#- hosts: all:localhost
#  roles:
#    # profiles

- hosts: localhost

  gather_facts: yes

  vars:
    vagrant_plugins:
      - vagrant-hosts
      - vagrant-vbox-snapshot
      - vagrant-aws
      - vagrant-vbguest

  tasks:

    - include_tasks: deploy-debian.yml
      become: yes
      # become_method: sudo
      when: ansible_os_family == 'Debian'
      tags: package

    - name: install extra user npm modules 
      npm:
        name: '{{ item }}'
        state: present
        global: yes
      with_items:
        - 'jsonlint'
      tags:
        - install-json-modules

    - name: install extra user pip modules 
      pip:
        name: '{{ item }}'
        state: present
        executable: pip2
        extra_args: --user
      with_items:
        - ansible-lint # https://github.com/willthames/ansible-lint
        - awscli   # http://docs.aws.amazon.com/cli/latest/userguide/getting-help.html
        - boto3    # https://boto3.readthedocs.io/en/latest/guide/quickstart.html
        - docker-compose
        - httpstat
        - jmespath-terminal  # https://github.com/jmespath/jmespath.terminal
        - molecule # https://molecule.readthedocs.io
        - pylint
        - pre-commit # https://pre-commit.com/
        - speedtest_cli
      tags:
        - install-pip-modules


    - name: "List installed vagrant plugins"
      command: "vagrant plugin list"
      register: vagrant_initial_plugins_list
      changed_when: no
      check_mode: no
      tags:
        - install-vagrant-plugins

    - name: "install vagrant plugins"
      command: "vagrant plugin install {{ item }}"
      register: install_vagrant_plugin
      with_items:
        "{{ vagrant_plugins }}"
      when: item not in vagrant_initial_plugins_list.stdout
      tags:
        - install-vagrant-plugins

