---
# tasks to copy profile files   


- name: copy profile files to users home directory
  template:
    src="{{ item }}.yml"
    dest="~/.{{ item }}"
  with_items:
    - devopsrc
    - vimrc
    - screenrc

- name: add devopsrc to .bashrc
  lineinfile:
    create=yes
    dest=~/.bashrc
    line=". ~/.devopsrc"

- name: check if there is a .profile
  stat: path=~/.profile
  register: file_dot_profile

- name: copy in a .profile if mssing
  copy:
    src: profile
    dest: ~/.profile
  when: file_dot_profile.stat.exists == False
