##---------------------------------------------------------------------------
## @(#)$Id$
##title          :.bashrc
##description    :Example devops workstation .bashrc file
##author         :Danny W Sheehan
##date           :March 2015
##
##  Configures bash prompt to include
##     - git - branch 
##     - Python environment - working project
##     - ruby environment - ruby and gem set versions
##
##  Also adjusts title bar of terminal session to correctly display host
##  you are logged in at.
##

# personal preferences.
# umask 0077
mkdir -p ~/.backups ~/.tmp ~/bin
export PROJECT_HOME=~/PROJECTS
export EDITOR=vi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# guard to avoid breaking scp and sftp if output is displayed.
# [[ $- == *i* ]] || return 0
#
# much quicker method
[ -z "$PS1" ] && return

export HISTCONTROL=ignoredups

# show colors when grepping through logs
my_grep_options=(--color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.svn)
alias grep='grep $my_grep_options' egrep='grep -E $my_grep_options' fgrep='grep -F $my_grep_options'


# User specific aliases and functions



set_titlebar() {
  case $TERM in
    *xterm*|ansi|rxvt)
      printf "\033]0;%s\007" "$*"
        ;;
    esac
}



mkcd()    { mkdir "$1" && cd "$1"; }
calc()    { awk "BEGIN{ print $* }" ;}
hex2dec() { echo $((16#$1)); }
dec2hex() { awk -v num=$1 'BEGIN { printf "%x\n", num}'; }
mktar()   { tar cztf "${1%%/}.tar.gz" "${1%%/}/"; }
bu()      { cp $1 ~/.backups/$(basename $1)-$(date +%Y%m%d%H%M).bk; }

get_sha() { git rev-parse --short HEAD 2>/dev/null; }

encrypt() { gpg -ac --no-options "$1"; }
decrypt() { gpg --no-options "$1"; }
weather() { curl "http://wttr.in/$1"; }


httpdebug () { /usr/bin/curl $@ -o /dev/null -w "dns: %{time_namelookup} connect: %{time_connect} pretransfer: %{time_pretransfer} starttransfer: %{time_starttransfer} total: %{time_total}\n" ; }

alias memhogs='ps wwaxm -o pid,stat,vsize,rss,time,command | head -10'
alias cpuhogs='ps wwaxr -o pid,stat,%cpu,time,command | head -10'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'

# osx only
trash()   { command mv "$@" ~/.Trash ; }
spotlight() { mdfind "kMDItemDisplayName == '$@'wc"; }


if [ -s /usr/share/git-core/contrib/completion/git-prompt.sh ];then
  source /usr/share/git-core/contrib/completion/git-prompt.sh
elif [ -s /usr/lib/git-core/git-sh-prompt ];then
  source /usr/lib/git-core/git-sh-prompt
elif [ -s ~/bin/git-prompt.sh ];then
  # wget https://github.com/git/git/raw/master/contrib/completion/git-prompt.sh
  source ~/bin/git-prompt.sh
else
  return
fi


if [ -s /usr/bin/virtualenvwrapper.sh ];then
  source /usr/bin/virtualenvwrapper.sh
elif [ -s /usr/local/bin/virtualenvwrapper.sh ];then
  source /usr/local/bin/virtualenvwrapper.sh
else 
  VENV=$(which virtualenvwrapper.sh 2> /dev/null)
  if [ -n "$VENV" ];then
    source $VENV
  fi
fi

export PATH="$PATH:$HOME/.rvm/bin" 
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 


# Reset
Color_Off="\[\033[0m\]"       # Text Reset

# Regular Colors
Black="\[\033[0;30m\]"        # Black
Red="\[\033[0;31m\]"          # Red
Green="\[\033[0;32m\]"        # Green
Yellow="\[\033[0;33m\]"       # Yellow
Blue="\[\033[0;34m\]"         # Blue
Purple="\[\033[0;35m\]"       # Purple
Cyan="\[\033[0;36m\]"         # Cyan
White="\[\033[0;37m\]"        # White

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUPSTREAM="auto"

PROMPT_COMMAND='__git_ps1 "[${Yellow}$(echo -e code $?)$Color_Off]\n${VIRTUAL_ENV:+[${Yellow}$(basename $VIRTUAL_ENV)$Color_Off]\n}${GEM_HOME:+[${Cyan}$(rvm-prompt i v p g)$Color_Off]\n}" "\h:\W \u\\\$ " "[%s $(get_sha)]\n";set_titlebar "$USER@${HOSTNAME%%.*} $(basename $PWD)"'
